products = [
    {
        'id': 'ID_1',
        'product_name': 'Product_1',
        'nutrition_grades': 'd',
        'selected_images': {'front': {'display': {'fr': 'some_img_1'}}},
        'url': 'off_url_1',
        'nutriments': {
            'energy_100g': 100,
            'fat_100g': 100,
            'saturated-fat_100g': 100,
            'carbohydrates_100g': 100,
            'sugars_100g': 100,
            'proteins_100g': 100,
            'salt_100g': 100},
        'categories_hierarchy': ['en:cat_1', 'it:cat_2',
                                 'en:cat_3', 'en:cat_4'],
        'stores_tags': ["Picard"]
    },
    {
        'id': 'ID_2',
        'product_name': 'Product_2',
        'nutrition_grades': 'a',
        'selected_images': {'front': {'display': {'fr': 'some_img_2'}}},
        'url': 'off_url_2',
        'nutriments': {
            'energy_100g': 100,
            'fat_100g': 100,
            'saturated-fat_100g': 100,
            'carbohydrates_100g': 100,
            'sugars_100g': 100,
            'proteins_100g': 100,
            'salt_100g': 100},
        'categories_hierarchy': ['en:cat_1', 'fr:cat_2',
                                 'en:cat_3', 'en:cat_4'],
        'stores_tags': ["Aldi", "Auchan"]
    },
    {
        'id': 'ID_3',
        'product_name': 'Product_3',
        'nutrition_grades': 'b',
        'selected_images': {'front': {'display': {'fr': 'some_img_3'}}},
        'url': 'off_url_3',
        'categories_hierarchy': ['en:cat_1', 'en:cat_2',
                                 'fr:cat_3', 'en:cat_5'],
        'stores_tags': ["None", "Foreign"]
    },
    {
        'id': 'ID_4',
        'product_name': 'Product_4',
        'nutrition_grades': 'e',
        'selected_images': {'front': {'display': {'fr': 'some_img_4'}}},
        'url': 'off_url_4',
        'categories_hierarchy': ['fr:cat_1', 'es:cat_2', 'de:cat_3'],
        'stores_tags': []
    },
    {
        'id': 'ID_5',
        'product_name': 'Product_5',
        'nutrition_grades': '',
        'selected_images': {'front': {'display': {'fr': 'some_img_5'}}},
        'url': 'off_url_5',
        'categories_hierarchy': ['de:cat_1', 'en:cat_2', 'fr:cat_3'],
        'stores_tags': ["Aldi"]
    },
    {
        'id': 'ID_2',
        'product_name': 'Double_Product_2',
        'nutrition_grades': 'a',
        'selected_images': {'front': {'display': {'fr': 'some_img_2'}}},
        'url': 'off_url_2',
        'categories_hierarchy': ['en:cat_1', 'fr:cat_2',
                                 'en:cat_3', 'en:cat_4'],
        'stores_tags': ["Auchan"]
    },
    {
        'id': 'ID_7',
        'product_name': 'Product_7',
        'nutrition_grades': 'b',
        'selected_images': {'front': {'display': {'fr': 'some_img_7'}}},
        'url': 'off_url_7',
        'nutriments': {
            'energy_100g': 100,
            'fat_100g': 100,
            'saturated-fat_100g': 100,
            'carbohydrates_100g': 100,
            'sugars_100g': 100,
            'proteins_100g': 100,
            'salt_100g': 100},
        'categories_hierarchy': ['en:cat_1', 'it:cat_2',
                                 'en:cat_3', 'en:cat_4'],
        'stores_tags': ["Aldi", "Auchan"]
    },
    {
        'id': 'ID_8',
        'product_name': 'Product_8',
        'nutrition_grades': 'b',
        'selected_images': {'front': {'display': {'fr': 'some_img_8'}}},
        'url': 'off_url_8',
        'nutriments': {
            'energy_100g': 100,
            'fat_100g': 100,
            'saturated-fat_100g': 100,
            'carbohydrates_100g': 100,
            'sugars_100g': 100,
            'proteins_100g': 100,
            'salt_100g': 100},
        'categories_hierarchy': ['en:cat_1', 'fr:cat_2',
                                 'en:cat_3', 'en:cat_4'],
        'stores_tags': ["Biocoop", "Carrefour"]
    },
    {
        'id': 'ID_9',
        'product_name': 'Product_9',
        'nutrition_grades': 'a',
        'selected_images': {'front': {'display': {'fr': 'some_img_9'}}},
        'url': 'off_url_9',
        'nutriments': {
            'energy_100g': 100,
            'fat_100g': 100,
            'saturated-fat_100g': 100,
            'carbohydrates_100g': 100,
            'sugars_100g': 100,
            'proteins_100g': 100,
            'salt_100g': 100},
        'categories_hierarchy': ['en:cat_1', 'it:cat_2',
                                 'en:cat_3', 'en:cat_4'],
        'stores_tags': ["Casino", "Cora"]
    },
    {
        'id': 'ID_10',
        'product_name': 'Product_10',
        'nutrition_grades': 'c',
        'selected_images': {'front': {'display': {'fr': 'some_img_10'}}},
        'url': 'off_url_10',
        'nutriments': {
            'energy_100g': 100,
            'fat_100g': 100,
            'saturated-fat_100g': 100,
            'carbohydrates_100g': 100,
            'sugars_100g': 100,
            'proteins_100g': 100,
            'salt_100g': 100},
        'categories_hierarchy': ['en:cat_1', 'fr:cat_2',
                                 'en:cat_3', 'en:cat_4'],
        'stores_tags': ["Franprix", "Intermarche"]
    },
    {
        'id': 'ID_11',
        'product_name': 'Product_11',
        'nutrition_grades': 'a',
        'selected_images': {'front': {'display': {'fr': 'some_img_11'}}},
        'url': 'off_url_11',
        'nutriments': {
            'energy_100g': 100,
            'fat_100g': 100,
            'saturated-fat_100g': 100,
            'carbohydrates_100g': 100,
            'sugars_100g': 100,
            'proteins_100g': 100,
            'salt_100g': 100},
        'categories_hierarchy': ['en:cat_1', 'it:cat_2',
                                 'en:cat_3', 'en:cat_4'],
        'stores_tags': ["Leader Price", "Leclerc"]
    },
    {
        'id': 'ID_12',
        'product_name': 'Product_12',
        'nutrition_grades': 'c',
        'selected_images': {'front': {'display': {'fr': 'some_img_12'}}},
        'url': 'off_url_12',
        'nutriments': {
            'energy_100g': 100,
            'fat_100g': 100,
            'saturated-fat_100g': 100,
            'carbohydrates_100g': 100,
            'sugars_100g': 100,
            'proteins_100g': 100,
            'salt_100g': 100},
        'categories_hierarchy': ['en:cat_1', 'fr:cat_2',
                                 'en:cat_3', 'en:cat_4'],
        'stores_tags': ["Lidl", "Magasins U"]
    },
    {
        'id': 'ID_13',
        'product_name': 'Product_13',
        'nutrition_grades': 'b',
        'selected_images': {'front': {'display': {'fr': 'some_img_13'}}},
        'url': 'off_url_13',
        'nutriments': {
            'energy_100g': 100,
            'fat_100g': 100,
            'saturated-fat_100g': 100,
            'carbohydrates_100g': 100,
            'sugars_100g': 100,
            'proteins_100g': 100,
            'salt_100g': 100},
        'categories_hierarchy': ['en:cat_1', 'de:cat_2',
                                 'en:cat_3', 'en:cat_4'],
        'stores_tags': ["Monoprix", "Picard"]
    },
    {
        'id': 'ID_14',
        'product_name': 'Product_14',
        'nutrition_grades': 'a',
        'selected_images': {'front': {'display': {'fr': 'some_img_14'}}},
        'url': 'off_url_14',
        'nutriments': {
            'energy_100g': 100,
            'fat_100g': 100,
            'saturated-fat_100g': 100,
            'carbohydrates_100g': 100,
            'sugars_100g': 100,
            'proteins_100g': 100,
            'salt_100g': 100},
        'categories_hierarchy': ['en:cat_1', 'fr:cat_2',
                                 'en:cat_3', 'en:cat_4'],
        'stores_tags': ["Aldi", "Auchan"]
    },
    {
        'id': 'ID_15',
        'product_name': 'Product_15',
        'nutrition_grades': 'b',
        'selected_images': {'front': {'display': {'fr': 'some_img_15'}}},
        'url': 'off_url_15',
        'nutriments': {
            'energy_100g': 100,
            'fat_100g': 100,
            'saturated-fat_100g': 100,
            'carbohydrates_100g': 100,
            'sugars_100g': 100,
            'proteins_100g': 100,
            'salt_100g': 100},
        'categories_hierarchy': ['en:cat_1', 'de:cat_2',
                                 'en:cat_3', 'en:cat_4'],
        'stores_tags': ["Biocoop", "Carrefour"]
    },
    {
        'id': 'ID_16',
        'product_name': 'Product_16',
        'nutrition_grades': 'c',
        'selected_images': {'front': {'display': {'fr': 'some_img_16'}}},
        'url': 'off_url_16',
        'nutriments': {
            'energy_100g': 100,
            'fat_100g': 100,
            'saturated-fat_100g': 100,
            'carbohydrates_100g': 100,
            'sugars_100g': 100,
            'proteins_100g': 100,
            'salt_100g': 100},
        'categories_hierarchy': ['en:cat_1', 'de:cat_2',
                                 'en:cat_3', 'en:cat_4'],
        'stores_tags': ["Casino", "Cora"]
    },
]
